name: Pull Request Checks

on:
  pull_request:
  workflow_dispatch:

jobs:

  # Linting - StyleLint + ESLint

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install >> lint_log.txt 2>&1

      - name: Run Stylelint
        run: bun run lint:css >> lint_log.txt 2>&1

      - name: Run linting checks
        run: bun run lint >> lint_log.txt 2>&1

      - name: Upload log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: prettier(fmt)
          path: lint_log.txt

  # ---------------------------------------------------------------------

  # Formating - Prettier

  Formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install > fmt_log.txt 2>&1 || exit 1

      - name: Run bun fmt
        run: bun fmt >> fmt_log.txt 2>&1

      - name: Upload log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: prettier(fmt)
          path: fmt_log.txt

  # ---------------------------------------------------------------------
